#!/bin/bash
runningMessage="----- Running Script -----"
finishingMessage="----- Finishing Terminal Script -----"



echo $runningMessage



echo Who are you?
read who
echo Hello, $who!

echo How old are you
read age
if [ "$age" -gt 20 ]
then 
    echo "You can drink."
else 
    echo "You are too Young to drink."
fi



echo $finishingMessage